### ISSUE TITLE
Number Input Format

### ISSUE THREAD

**Issue by Lukkaz** [jessehon/angular2-json-schema-form-ionic#24]
When creating an input for number values only the style is really off..

Any tips how to fix this and make it look like the other widgets?

![image](https://user-images.githubusercontent.com/5005962/45432885-eb9bff00-b678-11e8-97c5-dd84a37e068c.png)

**Comment by Lukkaz** [comment]
Code to replicate: 

```
{
"schema": {
    "type": "object",
    "properties": {
      "pname": {
        "title": "Position Title",
        "type": "string",
        "placeholder": "Answer Input"
      },
      "company": {
        "type": "string",
        "enum": [
          "Option1",
          "Option2"
        ]
      },
      "rate": {
        "title": "Pay Rate",
        "type": "number",  // type definition here
        "placeholder": "Answer Input"
      },
        "datepicker_6": {
        "type": "string",
        "format": "date"
      }
   }
}
```

**Comment by ramm24** [comment]
@Lukkaz 
That's a bug.
You could reuse the input component and add it for your widget library.

```
import { IonicInputComponent } from angular2-json-schema-form-ionic;
import { WidgetLibraryService} from 'angular2-json-schema-form;
...
constructor(private widgetLibrary: WidgetLibraryService) {
    widgetLibrary.registerWidget('number',  IonicInputComponent);
}
```
You can check the docs on https://github.com/dschnelldavis/angular2-json-schema-form.

**Comment by Lukkaz** [comment]
@ramm24 

Thank you I appreciate the workaround, I spent a few hours looking over the source last night and came across a few other bugs I am going to mess with over the next week or so. I will post any resolution to my findings for others.
